name: SageMaker Linear Learner main metaflow action

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Metaflow scripts => Run SageMaker Linear Learner ML Pipeline
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-2
          METAFLOW_DATASTORE_SYSROOT_S3: ${{ secrets.METAFLOW_DATASTORE_SYSROOT_S3 }}
          METAFLOW_DATATOOLS_SYSROOT_S3: ${{ secrets.METAFLOW_DATATOOLS_SYSROOT_S3 }}
          SAGEMAKER_EXECUTION_ROLE: ${{ secrets.SAGEMAKER_EXECUTION_ROLE }}
          METAFLOW_DEFAULT_DATASTORE:  ${{ secrets.METAFLOW_DEFAULT_DATASTORE }}
          python 'linear-learner.py' run

